server:
  port: 8072
spring:
  application:
    name: "api-gateway"
#  config:
#    import: "configserver:http://configserver-microservice:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
    httpclient:
      connect-timeout: 1000
      response-timeout: 2s
  services:
    api-gateway:
      build: .
      ports:
        - "8072:8072"
        - "5005:5005"   # expose debug port
      environment:
        JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted

  #this info enabled true is allowing to show info properties on Eureka dashBOARD
  info:
    env:
      enabled: true
info:
  app:
    name: "api-gateway"
    description: "API-Gateway micro service"
    version: "1.0.0"
logging:
  level:
    com:
      learning:
        api_gateway: DEBUG
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
