server:
  port: 8072
spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
  services:
    api-gateway:
      build: .
      ports:
        - "8072:8072"
        - "5005:5005"   # expose debug port
      environment:
        JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted

  #this info enabled true is allowing to show info properties on Eureka dashBOARD
  info:
    env:
      enabled: true
info:
  app:
    name: "api-gateway"
    description: "API-Gateway micro service"
    version: "1.0.0"
logging:
  level:
    com:
      learning:
        api_gateway: DEBUG
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
