spring:
  application:
    name: "eurekaserver"
  config:
    import: "configserver:http://localhost:8071/"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health: #this is to first make sure eureka server is live and ready to accept traffic then only start account/loan/card ms
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
