application:
  name: "eurekaserver"
server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true   # enables /actuator/health/liveness and /actuator/health/readiness
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false