#these properties are not required since we're not using spring now, its spring cloud config server
#spring:
#  config:
#    activate:
#      on-profile: "prod"
build:
  version: "1.0.0"

accounts:
  message: "welcome to accounts prod microservice apis"
  contactDetails:
    name: "Moazzam Khan - product owner"
    email: "moazzam@gmail.com"
  onCallSupport:
    -(555)555-1234
    -(555)523-1234