services:
  #1st service
  network-deploy-service:
    networks:
      - komalj
  #2nd service
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700mb

  microservice-mysql-config:
    extends: network-deploy-service
    image: mysql
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    environment:
      MYSQL_ROOT_PASSWORD: root

  #3rd service
  microservice-configserver-config:
    extends: microservice-base-config
    depends_on:
      configserver-microservice:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: "configserver:http://configserver-microservice:8071/"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
