server:
  port: 9091
spring:
  application:
    name: "cards"
  profiles:
    active: "qa"
  #Here we are mentioning where is our message queue
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: "guest"
    password: "guest"
  datasource:
    url: jdbc:mysql://localhost:3307/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  #this info enabled true is allowing to show info properties on Eureka dashBOARD
  info:
    env:
      enabled: true
#this endpoint at root level is different from management endpoint
endpoints:
  shutdown:
    enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
#This info is being displayed on Eureka dashboard
info:
  app:
    name: "cards"
    description: "Cards micro service"
    version: "1.0.0"
