server:
  port: 8090
spring:
  application:
    name: "loans"
  config:
    import: "configserver:http://localhost:8071/"
  #Here we are mentioning where is our message queue
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
#commenting H2 db conf since we are going to use mysql db
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  datasource:
    url: jdbc:mysql:localhost://3308/loansdb
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
